### ISSUE TITLE
Unnecessary disambiguation in SAN generator

### ISSUE THREAD

**Issue by sb362** [ellxor/uchess#4]
`generate_san()` disambiguates when two pieces from either side can move to the same square.
For example in the position
`8/5b1k/7P/5PK1/6B1/8/8/8 w - - 1 79`
 `generate_san()` yields `Bgh5` when it should be `Bh5`

**Comment by ellxor** [comment]
Thank you for pointing out this bug :+1: 
Commit 091262b5db7e173c80233a62d4269b7fc3dbcb38 should fix it.
